[package]
name = "solana-client-helpers"
version = "0.1.0"
authors = ["Alexander XX <freecoder.xx@gmail.com>"]
edition = "2018"

[dependencies]
solana-program = "1.5.15"
solana-sdk = "1.5.15"
solana-client = "1.5.15"
spl-token = { version = "3.1.0", features = ["no-entrypoint"] }
spl-token-swap = { git = "https://github.com/solana-labs/solana-program-library.git", features = ["no-entrypoint"] }
spl-associated-token-account = { version = "1.0.2", features = ["no-entrypoint"] }
